apiVersion: v1
kind: Service
metadata:
  annotations:
  name: mysql
spec:
  externalName: mysql.mysql.svc.cluster.local
  ports:
  - name: discovery
    port: 3306
  selector:
    app: mysql
  type: ExternalName
